<?php

namespace Wlalele\Bundle\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getArticlesByProductId($id)
    {
        return $this->createQueryBuilder('s')
                    ->select()
                    ->where('s.product ='.$id)
                    ->getQuery()
                    ->execute();
    }
}
