<?php

namespace Wlalele\Bundle\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findRandomly()
    {
        return $this->createQueryBuilder('p')
                    ->addSelect('RAND() as HIDDEN rand')
                    ->orderBy('rand')
                    ->getQuery()
                    ->execute();
    }
}
