security:
    providers:
        in_memory:
            memory:
                users:
                    wlalele: { password: f638477e5a3d08a29421ae7d5ed616b2789e200b, roles: 'ROLE_ADMIN' }
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/
            anonymous: ~
            form_login: ~
            logout: ~
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }